# Generated by Django 5.1 on 2024-08-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('inventoryStatus', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.CharField(default=None, max_length=1024)),
                ('rating', models.CharField(default=None, max_length=1024)),
            ],
        ),
    ]
